home:
    path: /
    controller: App\Controller\FrontController::index
app_login:
    path: /login/
    controller: App\Controller\SecurityController::login
url_shortener_new:
    path: /url/newurl
    controller: App\Controller\UrlController::newUrlShortener
buscador_url_real:
    path: /buscarUrlReal
    controller: App\Controller\UrlController::buscarUrlOriginal
url_corta:
    path: /{urlCorta}
    controller: App\Controller\UrlController::redirectToOriginalUrl
show_url_real:
    path: /{urlReal}
    controller: App\Controller\UrlController::showOriginalUrl
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout



