home:
    path: /
    controller: App\Controller\FrontController::index
app_login:
    path: /login/
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
url_shortener_new:
    path: /url/newurl
    controller: App\Controller\UrlController::newUrlShortener
buscador_url_real:
    path: /buscarUrlRealarUrls
    controller: App\Controller\UrlController::buscarUrlOriginal
redireccion_url_real:
    path: /{urlCorta}
    controller: App\Controller\UrlController::redirectUrlReal
listado_urls:
    path: /urls/list
    controller: App\Controller\UserController::listarUrls




